# src/chat_system.py

import asyncio
import json
import logging
import re
import time
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Coroutine, Dict, List, Optional, Set, Tuple
from urllib.parse import urlparse

from config.global_config import MAX_TOOL_CALLS, MAX_CACHED_API_REQUESTS, \
    PENDING_CONFIRMATION_TIMEOUT
from src.clients.zammad_client import ZammadClient
from src.database.memory_manager import MemoryManager
from src.engine import LLMCommunicationError, TextEngine
from src.message_handler import BotLogic
from src.persona import Persona, ExecutionMode, MemoryMode
from src.tools.definitions import WRITE_TOOLS, ZAMMAD_TOOLS, MODEL_INCOMPATIBLE_TOOLS
from src.tools.tool_manager import ToolManager
from src.utils.model_utils import get_model_list
from src.utils.save_utils import load_personas_from_file, save_personas_to_file

logger = logging.getLogger(__name__)


def _get_model_prefix(model_name: str) -> str:
    """Return the model family prefix using the same logic as engine.py routing."""
    if model_name.startswith("gpt"):
        return "gpt"
    elif "claude" in model_name:
        return "claude"
    elif "gemma" in model_name:
        return "gemma"
    elif "gemini-3.1" in model_name:
        return "gemini-3.1"
    elif "gemini" in model_name:
        return "gemini"
    elif model_name == "local":
        return "local"
    return "unknown"


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()
    PENDING_CONFIRMATION = auto()


@dataclass
class PendingConfirmation:
    """Stores state for a tool call awaiting user approval in CONFIRM mode."""
    write_calls: List[Dict[str, Any]]
    conversation_history: List[Dict[str, Any]]
    persona_name: str
    tools_for_llm: List[Dict[str, Any]]
    ticket_to_log: Optional[int]
    image_url: Optional[str]
    customer_id: Optional[int] = None
    created_at: float = field(default_factory=time.time)


class ChatSystem:
    def __init__(self, memory_manager: MemoryManager, text_engine: TextEngine, zammad_client: ZammadClient) -> None:
        self.personas: Dict[str, Persona] = load_personas_from_file() or {}
        self.memory_manager: MemoryManager = memory_manager
        self.text_engine: TextEngine = text_engine
        self.zammad_client: ZammadClient = zammad_client
        self.tool_manager: ToolManager = ToolManager(zammad_client)
        self.bot_logic: BotLogic = BotLogic(self)
        self.last_api_requests: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = defaultdict(dict)
        self.models_available: Dict[str, Any] = get_model_list() or {}
        self.background_tasks: Set[Coroutine[Any, Any, Any]] = set()
        self._pending_confirmations: Dict[Tuple[str, str], PendingConfirmation] = {}

    def _store_api_request(self, user_identifier: str, persona_name: str,
                           payload: Dict[str, Any]) -> None:
        """Stores the last API request payload, evicting the oldest user entry if over capacity."""
        self.last_api_requests[user_identifier][persona_name] = payload
        if len(self.last_api_requests) > MAX_CACHED_API_REQUESTS:
            oldest_key = next(iter(self.last_api_requests))
            del self.last_api_requests[oldest_key]

    def _find_ticket_number_in_message(self, message: str) -> Optional[int]:
        """Finds a ticket NUMBER pattern like [Ticket#12345] in a message."""
        match = re.search(r'\[Ticket#(\d+)\]', message, re.IGNORECASE)
        if match:
            return int(match.group(1))
        return None

    async def _get_ticket_id_from_number(self, ticket_number: int) -> Optional[int]:
        """Translates a user-facing ticket number to an internal Zammad ticket ID."""
        try:
            search_results = await asyncio.to_thread(
                self.zammad_client.search_tickets, query=f"number:{ticket_number}"
            )
            if search_results:
                return search_results[0]['id']
            return None
        except Exception as e:
            logger.error(f"Error searching for ticket number {ticket_number}: {e}", exc_info=True)
            return None

    async def _find_active_ticket_for_user(self, customer_id: int) -> Optional[int]:
        """Finds the most recently updated open or new ticket for a given Zammad user ID."""
        try:
            query = f"customer_id:{customer_id} AND state.name:(open OR new)"
            search_results: List[Dict[str, Any]] = await asyncio.to_thread(
                self.zammad_client.search_tickets,
                query=query,
                sort_by='updated_at',
                order_by='desc'
            )
            if search_results:
                return search_results[0]['id']
            return None
        except Exception as e:
            logger.error(f"Error searching for active tickets for customer {customer_id}: {e}", exc_info=True)
            return None

    async def _get_or_create_zammad_user(self, user_identifier: str, channel: str,
                                         user_display_name: Optional[str] = None) -> Tuple[
        Optional[int], Optional[str]]:
        """
        Finds a Zammad user by email or creates one. Uses display name for better user creation.
        Returns a tuple of (Zammad user ID, Zammad-registered email).
        """
        email_match: Optional[re.Match[str]] = re.search(r'<(.+?)>', user_identifier)
        is_real_email: bool = email_match is not None

        email: str
        firstname: str
        lastname: str
        note: Optional[str]

        if is_real_email:
            email = email_match.group(1)
            name_part: str = user_display_name if user_display_name else user_identifier.split('<')[0].strip()
            name_parts: List[str] = name_part.split()
            firstname = name_parts[0] if name_parts else "Unknown"
            lastname = ' '.join(name_parts[1:]) if len(name_parts) > 1 else "User"
            note = None
        else:
            domain: str = urlparse(self.zammad_client.api_url).hostname or "local.host"
            email = f"{channel.lower()}-{user_identifier}@{domain}"
            name_parts = user_display_name.split() if user_display_name else [f"{channel.capitalize()} User",
                                                                              user_identifier]
            firstname = name_parts[0]
            lastname = ' '.join(name_parts[1:]) if len(name_parts) > 1 else ""
            note = f"Auto-generated user from {channel.capitalize()}. Original identifier: {user_identifier}"

        try:
            search_results = await asyncio.to_thread(self.zammad_client.search_user, email)
            if search_results:
                return search_results[0]['id'], search_results[0]['email']

            logger.info(f"Creating new Zammad user for identifier '{user_identifier}' with email: {email}")
            new_user = await asyncio.to_thread(
                self.zammad_client.create_user,
                email=email, firstname=firstname, lastname=lastname, note=note
            )
            return new_user['id'], new_user['email']

        except Exception as e:
            logger.error(f"Error getting or creating Zammad user for '{user_identifier}': {e}", exc_info=True)
            return None, None

    def _format_raw_history_for_llm(self, raw_history: List[Dict[str, Any]], memory_mode: str,
                                    persona_name: str, server_id: Optional[str]) -> List[Dict[str, Any]]:
        """Formats database history records into a list of messages for the LLM."""
        final_history: List[Dict[str, Any]] = []
        is_group_chat = memory_mode in ("server", "global", "ticket") or (
                    memory_mode == "channel" and server_id is not None)

        for msg in raw_history:
            author_role = msg.get('author_role')
            author_name = msg.get('author_name')
            content = msg.get('content', '')

            if author_role == 'user':
                if is_group_chat and author_name:
                    formatted_content = f"{author_name}: {content}"
                    final_history.append({'role': 'user', 'content': formatted_content})
                else:
                    final_history.append({'role': 'user', 'content': content})
            elif author_role == 'assistant':
                if author_name == persona_name:
                    final_history.append({'role': 'assistant', 'content': content})
                else:
                    # In a group chat, messages from other personas are treated as user messages
                    formatted_content = f"{author_name}: {content}"
                    final_history.append({'role': 'user', 'content': formatted_content})
        return final_history

    async def generate_response(
            self,
            persona_name: str,
            user_identifier: str,
            channel: str,
            message: str,
            server_id: Optional[str] = None,
            image_url: Optional[str] = None,
            history_limit: Optional[int] = None,
            user_display_name: Optional[str] = None
    ) -> Tuple[str, ResponseType, Optional[int]]:
        command_result: Optional[Dict[str, Any]] = await self.bot_logic.preprocess_message(persona_name,
                                                                                           user_identifier, message)
        if command_result:
            mutated = command_result.get("mutated", False)
            if mutated:
                save_personas_to_file(self.personas)
            return command_result["response"], ResponseType.DEV_COMMAND, None

        ticket_to_log: Optional[int] = None
        try:
            persona: Optional[Persona] = self.personas.get(persona_name)
            if not persona:
                return "Error: Persona not found.", ResponseType.DEV_COMMAND, None

            is_zammad_aware: bool = persona.get_zammad_aware()
            customer_id: Optional[int] = None
            zammad_email: Optional[str] = None
            mode = persona.get_memory_mode()
            user_facing_ticket_number: Optional[int] = None

            if is_zammad_aware:
                customer_id, zammad_email = await self._get_or_create_zammad_user(user_identifier, channel,
                                                                                  user_display_name)
                if customer_id:
                    user_facing_ticket_number = self._find_ticket_number_in_message(message)
                    if user_facing_ticket_number:
                        ticket_to_log = await self._get_ticket_id_from_number(user_facing_ticket_number)
                        if not ticket_to_log:
                            logger.warning(
                                f"User mentioned ticket number {user_facing_ticket_number}, but it was not found.")
                    else:
                        ticket_to_log = await self._find_active_ticket_for_user(customer_id)

            effective_limit: int = persona.get_context_length()
            if history_limit is not None:
                effective_limit = min(effective_limit, history_limit)

            raw_history: List[Dict[str, Any]] = []
            memory_mode_used = "none"
            system_context_message: Optional[str] = None

            if mode == MemoryMode.TICKET_ISOLATED:
                memory_mode_used = "ticket"
                if ticket_to_log:
                    raw_history = self.memory_manager.get_ticket_history(ticket_to_log, effective_limit)
            elif mode == MemoryMode.SERVER_WIDE:
                if server_id:
                    memory_mode_used = "server"
                    raw_history = self.memory_manager.get_server_history(server_id, persona_name, effective_limit)
                else:
                    memory_mode_used = "server (unavailable)"
            elif mode == MemoryMode.PERSONAL:
                memory_mode_used = "personal"
                raw_history = self.memory_manager.get_personal_history(user_identifier, persona_name, effective_limit)
            elif mode == MemoryMode.GLOBAL:
                memory_mode_used = "global"
                raw_history = self.memory_manager.get_global_history(persona_name, effective_limit)
            elif mode == MemoryMode.CHANNEL_ISOLATED:
                memory_mode_used = "channel"
                raw_history = self.memory_manager.get_channel_history(channel, persona_name, server_id, effective_limit)

            if memory_mode_used == "ticket" and ticket_to_log:
                display_number = user_facing_ticket_number or ticket_to_log
                system_context_message = f"This conversation is part of Zammad ticket #{display_number}."

            conversation_history: List[Dict[str, Any]] = self._format_raw_history_for_llm(raw_history, memory_mode_used,
                                                                                          persona_name, server_id)
            if system_context_message:
                conversation_history.insert(0, {"role": "system", "content": system_context_message})

            all_tools = self.tool_manager.get_tool_definitions()
            enabled_tool_names = persona.get_enabled_tools()
            tools_for_llm: List[Dict[str, Any]] = []
            if enabled_tool_names == ['*']:
                tools_for_llm = all_tools
            elif enabled_tool_names:
                tools_for_llm = [tool for tool in all_tools if
                                 tool.get('function', {}).get('name') in enabled_tool_names]

            if not is_zammad_aware:
                tools_for_llm = [t for t in tools_for_llm
                                 if t.get('function', {}).get('name') not in ZAMMAD_TOOLS]

            model_prefix = _get_model_prefix(persona.get_model_name())
            tools_for_llm = [t for t in tools_for_llm
                             if model_prefix not in MODEL_INCOMPATIBLE_TOOLS.get(
                                 t.get('function', {}).get('name'), set())]

            if is_zammad_aware and ticket_to_log:
                await asyncio.to_thread(self.zammad_client.add_article_to_ticket, ticket_id=ticket_to_log,
                                        body=message, impersonate_email=zammad_email)

            conversation_history.append({"role": "user", "content": message})

            for i in range(MAX_TOOL_CALLS):
                context_object: Dict[str, Any] = {
                    "persona_prompt": persona.get_prompt(),
                    "history": conversation_history,
                    "current_message": {"text": "", "image_url": image_url if i == 0 else None}
                }
                llm_response, api_payload = await self.text_engine.generate_response(
                    persona.get_config_for_engine(), context_object, tools=tools_for_llm
                )
                if api_payload: self._store_api_request(user_identifier, persona_name, api_payload)

                if llm_response.get("type") == "text":
                    final_text = llm_response.get("content", "")
                    if is_zammad_aware and ticket_to_log:
                        await asyncio.to_thread(self.zammad_client.add_article_to_ticket, ticket_id=ticket_to_log,
                                                body=final_text)
                    return final_text, ResponseType.LLM_GENERATION, ticket_to_log

                elif llm_response.get("type") == "tool_calls":
                    calls = llm_response.get("calls", [])
                    conversation_history.append({"role": "assistant", "tool_calls": calls})

                    is_confirm_mode = persona.get_execution_mode() == ExecutionMode.CONFIRM
                    read_calls = [c for c in calls if c.get("name") not in WRITE_TOOLS]
                    write_calls = [c for c in calls if c.get("name") in WRITE_TOOLS]

                    # Execute read-only tools immediately (even in CONFIRM mode)
                    for call_item in read_calls:
                        tool_name = call_item.get("name")
                        tool_args = call_item.get("arguments", {})
                        tool_result = await self.tool_manager.execute_tool(tool_name, **tool_args)
                        conversation_history.append({
                            "role": "tool",
                            "tool_call_id": call_item.get("id"),
                            "name": tool_name,
                            "content": json.dumps(tool_result)
                        })

                    # In CONFIRM mode, pause on write tools for user approval
                    if is_confirm_mode and write_calls:
                        pending = PendingConfirmation(
                            write_calls=write_calls,
                            conversation_history=conversation_history,
                            persona_name=persona_name,
                            tools_for_llm=tools_for_llm,
                            ticket_to_log=ticket_to_log,
                            image_url=image_url,
                            customer_id=customer_id
                        )
                        self._pending_confirmations[(user_identifier, persona_name)] = pending

                        descriptions = []
                        for wc in write_calls:
                            descriptions.append(f"- **{wc.get('name')}**: {json.dumps(wc.get('arguments', {}))}")
                        confirm_msg = "I'd like to perform the following actions:\n" + "\n".join(descriptions)
                        return confirm_msg, ResponseType.PENDING_CONFIRMATION, ticket_to_log

                    # AUTONOMOUS mode (or CONFIRM with no write tools): execute all write tools
                    for call_item in write_calls:
                        tool_name = call_item.get("name")
                        tool_args = call_item.get("arguments", {})

                        if tool_name == 'create_ticket':
                            if 'customer_id' not in tool_args and customer_id:
                                tool_args['customer_id'] = customer_id

                        tool_result = await self.tool_manager.execute_tool(tool_name, **tool_args)

                        if tool_name == 'create_ticket' and tool_result.get('result', {}).get('id'):
                            ticket_to_log = tool_result['result']['id']

                        conversation_history.append({
                            "role": "tool",
                            "tool_call_id": call_item.get("id"),
                            "name": tool_name,
                            "content": json.dumps(tool_result)
                        })
                else:
                    raise LLMCommunicationError("LLM returned an invalid response structure.")

            logger.error(f"Exceeded max tool calls ({MAX_TOOL_CALLS}) for user {user_identifier}.")
            return "I seem to be stuck in a loop. Could you please clarify your request?", ResponseType.DEV_COMMAND, ticket_to_log

        except LLMCommunicationError as e:
            logger.error(f"A recoverable LLM communication error occurred for {user_identifier}: {e}")
            if e.api_payload:
                self._store_api_request(user_identifier, persona_name, e.api_payload)
            error_msg = ("I'm not sure how to continue. Could you please rephrase?" if "empty response" in str(e) else
                         "Error while generating a response: " + str(e))
            return error_msg, ResponseType.DEV_COMMAND, ticket_to_log
        except Exception as e:
            logger.error(f"A critical error occurred in generate_response for {user_identifier}: {e}", exc_info=True)
            return "An internal error occurred while processing your request.", ResponseType.DEV_COMMAND, ticket_to_log

    async def resume_pending_confirmation(
            self, user_identifier: str, persona_name: str, approved: bool
    ) -> Tuple[str, ResponseType, Optional[int]]:
        """Resumes a tool execution that was paused for user confirmation."""
        key = (user_identifier, persona_name)
        pending = self._pending_confirmations.pop(key, None)

        if not pending:
            return "No pending confirmation found.", ResponseType.DEV_COMMAND, None

        if time.time() - pending.created_at > PENDING_CONFIRMATION_TIMEOUT:
            return "Confirmation expired. Please try again.", ResponseType.DEV_COMMAND, None

        persona = self.personas.get(pending.persona_name)
        if not persona:
            return "Error: Persona not found.", ResponseType.DEV_COMMAND, None

        conversation_history = pending.conversation_history
        ticket_to_log = pending.ticket_to_log

        try:
            if approved:
                for call_item in pending.write_calls:
                    tool_name = call_item.get("name")
                    tool_args = call_item.get("arguments", {})

                    if tool_name == 'create_ticket':
                        if 'customer_id' not in tool_args and pending.customer_id:
                            tool_args['customer_id'] = pending.customer_id

                    tool_result = await self.tool_manager.execute_tool(tool_name, **tool_args)

                    if tool_name == 'create_ticket' and tool_result.get('result', {}).get('id'):
                        ticket_to_log = tool_result['result']['id']

                    conversation_history.append({
                        "role": "tool",
                        "tool_call_id": call_item.get("id"),
                        "name": tool_name,
                        "content": json.dumps(tool_result)
                    })
            else:
                for call_item in pending.write_calls:
                    conversation_history.append({
                        "role": "tool",
                        "tool_call_id": call_item.get("id"),
                        "name": call_item.get("name"),
                        "content": json.dumps({"error": "Tool call denied by user"})
                    })

            # Continue the LLM conversation with the tool results
            context_object = {
                "persona_prompt": persona.get_prompt(),
                "history": conversation_history,
                "current_message": {"text": "", "image_url": None}
            }
            llm_response, api_payload = await self.text_engine.generate_response(
                persona.get_config_for_engine(), context_object, tools=pending.tools_for_llm
            )
            if api_payload:
                self._store_api_request(user_identifier, persona_name, api_payload)

            final_text = llm_response.get("content", "")
            return final_text, ResponseType.LLM_GENERATION, ticket_to_log

        except Exception as e:
            logger.error(f"Error resuming pending confirmation for {user_identifier}: {e}", exc_info=True)
            return "An error occurred while processing the confirmed action.", ResponseType.DEV_COMMAND, ticket_to_log
