# src/chat_system.py

import json
import logging
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any, Coroutine, Dict, List, Optional, Set, Tuple

from config.global_config import MAX_TOOL_CALLS, MAX_CACHED_API_REQUESTS, \
    PENDING_CONFIRMATION_TIMEOUT, MEMORY_RETRIEVAL_ENABLED, MEMORY_MAX_SUMMARIES_IN_CONTEXT
from src.clients.service_integration import ServiceIntegration
from src.database.memory_manager import MemoryManager
from src.engine import LLMCommunicationError, TextEngine
from src.message_handler import BotLogic
from src.persona import Persona, ExecutionMode, MemoryMode
from src.tools.definitions import WRITE_TOOLS, MODEL_INCOMPATIBLE_TOOLS
from src.tools.tool_manager import ToolManager, WebSearchHandler
from src.utils.model_utils import get_model_list, get_model_prefix
from src.utils.save_utils import load_personas_from_file, save_personas_to_file

logger = logging.getLogger(__name__)


def _relative_time(dt: datetime) -> str:
    """Format a datetime as a relative time string (e.g., '2 days ago')."""
    now = datetime.now(dt.tzinfo) if dt.tzinfo else datetime.now()
    delta = now - dt
    seconds = int(delta.total_seconds())
    if seconds < 0:
        return "just now"
    if seconds < 60:
        return "just now"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes} minute{'s' if minutes != 1 else ''} ago"
    hours = minutes // 60
    if hours < 24:
        return f"{hours} hour{'s' if hours != 1 else ''} ago"
    days = hours // 24
    if days < 7:
        return f"{days} day{'s' if days != 1 else ''} ago"
    weeks = days // 7
    if weeks < 5:
        return f"{weeks} week{'s' if weeks != 1 else ''} ago"
    months = days // 30
    if months < 12:
        return f"{months} month{'s' if months != 1 else ''} ago"
    years = days // 365
    return f"{years} year{'s' if years != 1 else ''} ago"


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()
    PENDING_CONFIRMATION = auto()


@dataclass
class PendingConfirmation:
    """Stores state for a tool call awaiting user approval in CONFIRM mode."""
    write_calls: List[Dict[str, Any]]
    conversation_history: List[Dict[str, Any]]
    persona_name: str
    tools_for_llm: List[Dict[str, Any]]
    image_url: Optional[str]
    created_at: float = field(default_factory=time.time)


@dataclass
class RequestContext:
    """Bundles resolved pipeline state flowing through generate_response phases."""
    persona: Persona
    persona_name: str
    user_identifier: str
    channel: str
    message: str
    server_id: Optional[str] = None
    image_url: Optional[str] = None
    history_limit: Optional[int] = None
    user_display_name: Optional[str] = None
    # Populated during _prepare_request
    conversation_history: List[Dict[str, Any]] = field(default_factory=list)
    tools_for_llm: List[Dict[str, Any]] = field(default_factory=list)
    oldest_interaction_id: Optional[int] = None


class ChatSystem:
    def __init__(self, memory_manager: MemoryManager, text_engine: TextEngine) -> None:
        self.personas: Dict[str, Persona] = load_personas_from_file() or {}
        self.memory_manager: MemoryManager = memory_manager
        self.text_engine: TextEngine = text_engine
        self.tool_manager: ToolManager = ToolManager()
        WebSearchHandler().register(self.tool_manager)
        self.bot_logic: BotLogic = BotLogic(self)
        self.last_api_requests: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = defaultdict(dict)
        self.models_available: Dict[str, Any] = get_model_list() or {}
        self.background_tasks: Set[Coroutine[Any, Any, Any]] = set()
        self._pending_confirmations: Dict[Tuple[str, str], PendingConfirmation] = {}
        self._services: Dict[str, ServiceIntegration] = {}
        self._embedding_service: Optional[Any] = None  # Set by MemoryAgent on first deploy

    def register_service(self, service: ServiceIntegration) -> None:
        """Register a service integration and its tools."""
        self._services[service.name] = service
        service.register_tools(self.tool_manager)
        logger.info(f"Registered service integration: {service.name}")

    def _store_api_request(self, user_identifier: str, persona_name: str,
                           payload: Dict[str, Any],
                           tools_for_llm: Optional[List[Dict[str, Any]]] = None) -> None:
        """Stores the last API request payload, evicting the oldest user entry if over capacity."""
        if tools_for_llm is not None:
            payload["_tools_for_llm"] = tools_for_llm
        else:
            existing = self.last_api_requests.get(user_identifier, {}).get(persona_name)
            if existing and "_tools_for_llm" in existing:
                payload["_tools_for_llm"] = existing["_tools_for_llm"]
        self.last_api_requests[user_identifier][persona_name] = payload
        if len(self.last_api_requests) > MAX_CACHED_API_REQUESTS:
            oldest_key = next(iter(self.last_api_requests))
            del self.last_api_requests[oldest_key]

    def _format_raw_history_for_llm(self, raw_history: List[Dict[str, Any]], memory_mode: str,
                                    persona_name: str, server_id: Optional[str]) -> List[Dict[str, Any]]:
        """Formats database history records into a list of messages for the LLM."""
        final_history: List[Dict[str, Any]] = []
        is_group_chat = memory_mode in ("server", "global", "ticket") or (
                    memory_mode == "channel" and server_id is not None)

        for msg in raw_history:
            author_role = msg.get('author_role')
            author_name = msg.get('author_name')
            content = msg.get('content', '')

            if author_role == 'user':
                if is_group_chat and author_name:
                    formatted_content = f"{author_name}: {content}"
                    final_history.append({'role': 'user', 'content': formatted_content})
                else:
                    final_history.append({'role': 'user', 'content': content})
            elif author_role == 'assistant':
                if author_name == persona_name:
                    tool_context_json = msg.get('tool_context')
                    if tool_context_json:
                        final_history.extend(json.loads(tool_context_json))
                    final_history.append({'role': 'assistant', 'content': content})
                else:
                    # In a group chat, messages from other personas are treated as user messages
                    formatted_content = f"{author_name}: {content}"
                    final_history.append({'role': 'user', 'content': formatted_content})
        return final_history

    async def _execute_write_calls(
            self,
            write_calls: List[Dict[str, Any]],
            conversation_history: List[Dict[str, Any]]
    ) -> None:
        """Execute write tool calls and append results to history."""
        for call_item in write_calls:
            tool_name: str = call_item.get("name", "")
            tool_args = call_item.get("arguments", {})
            tool_result = await self.tool_manager.execute_tool(tool_name, **tool_args)
            conversation_history.append({
                "role": "tool",
                "tool_call_id": call_item.get("id"),
                "name": tool_name,
                "content": json.dumps(tool_result)
            })

    @staticmethod
    def _append_denied_tool_results(
            write_calls: List[Dict[str, Any]],
            conversation_history: List[Dict[str, Any]]
    ) -> None:
        """Appends denial results for write tools the user rejected."""
        for call_item in write_calls:
            conversation_history.append({
                "role": "tool",
                "tool_call_id": call_item.get("id"),
                "name": call_item.get("name"),
                "content": json.dumps({"error": "Tool call denied by user"})
            })

    def _fetch_raw_history(
            self,
            mode: MemoryMode,
            persona_name: str,
            user_identifier: str,
            channel: str,
            server_id: Optional[str],
            effective_limit: int
    ) -> Tuple[List[Dict[str, Any]], str]:
        """Dispatches history retrieval based on memory mode. Returns (raw_history, mode_label)."""
        if mode == MemoryMode.TICKET_ISOLATED:
            return [], "ticket"
        elif mode == MemoryMode.SERVER_WIDE:
            if server_id:
                return self.memory_manager.get_server_history(server_id, persona_name, effective_limit), "server"
            return [], "server (unavailable)"
        elif mode == MemoryMode.PERSONAL:
            return self.memory_manager.get_personal_history(user_identifier, persona_name, effective_limit), "personal"
        elif mode == MemoryMode.GLOBAL:
            return self.memory_manager.get_global_history(persona_name, effective_limit), "global"
        else:
            return self.memory_manager.get_channel_history(channel, persona_name, server_id, effective_limit), "channel"

    def _build_conversation_history(
            self,
            persona: Persona,
            user_identifier: str,
            channel: str,
            server_id: Optional[str],
            history_limit: Optional[int]
    ) -> Tuple[List[Dict[str, Any]], Optional[int]]:
        """Retrieves and formats conversation history based on the persona's memory mode.

        Returns (formatted_history, oldest_interaction_id).
        oldest_interaction_id is the interaction_id of the oldest message in the
        sliding window, used for the memory recency filter.
        """
        persona_name = persona.get_name()

        effective_limit: int = persona.get_context_length()
        if history_limit is not None:
            effective_limit = min(effective_limit, history_limit)

        raw_history, memory_mode_used = self._fetch_raw_history(
            persona.get_memory_mode(), persona_name,
            user_identifier, channel, server_id, effective_limit
        )

        oldest_interaction_id = None
        if raw_history:
            oldest_interaction_id = raw_history[0].get('interaction_id')

        formatted = self._format_raw_history_for_llm(raw_history, memory_mode_used, persona_name, server_id)
        return formatted, oldest_interaction_id

    async def _retrieve_memory_block(
            self,
            persona: Persona,
            user_identifier: str,
            channel: str,
            server_id: Optional[str],
            conversation_history: List[Dict[str, Any]],
            oldest_interaction_id: Optional[int] = None,
    ) -> Optional[str]:
        """Retrieve and format relevant long-term memory summaries for injection.

        Returns a formatted <memory> block string, or None if no relevant memories
        or the feature is disabled.
        """
        if not MEMORY_RETRIEVAL_ENABLED or self._embedding_service is None:
            return None

        from src.embedding_service import EmbeddingService

        # Map MemoryMode enum to string for retrieve_relevant_summaries
        mode_map = {
            MemoryMode.CHANNEL_ISOLATED: "channel",
            MemoryMode.SERVER_WIDE: "server",
            MemoryMode.PERSONAL: "personal",
            MemoryMode.GLOBAL: "global",
            MemoryMode.TICKET_ISOLATED: "ticket",
        }
        memory_mode = mode_map.get(persona.get_memory_mode(), "channel")

        # Fetch candidate summaries
        summaries = self.memory_manager.retrieve_relevant_summaries(
            persona_name=persona.get_name(),
            channel=channel,
            server_id=server_id,
            user_identifier=user_identifier,
            memory_mode=memory_mode,
            include_ambient=persona.get_include_ambient_memory(),
            exclude_after_interaction_id=oldest_interaction_id,
            model_name=self._embedding_service.model_name,
        )

        if not summaries:
            return None

        # Extract text content from conversation history for embedding
        window_texts = []
        for msg in conversation_history:
            content = msg.get('content', '')
            if isinstance(content, str) and content.strip():
                window_texts.append(content)

        if not window_texts:
            return None

        # Embed the sliding window messages (1 batched API call)
        try:
            window_embeddings = await self._embedding_service.encode(window_texts)
        except Exception as e:
            logger.warning(f"Memory retrieval: embedding failed: {e}")
            return None

        if not window_embeddings:
            logger.warning("Memory retrieval: encode returned empty results")
            return None

        # Score each summary: max similarity across all window messages
        scored = []
        for summary in summaries:
            summary_emb = summary['embedding']
            max_sim = max(
                EmbeddingService.cosine_similarity(summary_emb, w_emb)
                for w_emb in window_embeddings
            )
            scored.append((max_sim, summary))

        # Sort by similarity (highest first) and take top-K
        scored.sort(key=lambda x: x[0], reverse=True)
        top_summaries = scored[:MEMORY_MAX_SUMMARIES_IN_CONTEXT]

        # Format memory block
        return self._format_memory_block(top_summaries)

    @staticmethod
    def _format_memory_block(scored_summaries: List[Tuple[float, Dict[str, Any]]]) -> Optional[str]:
        """Format scored summaries into a <memory> block for injection."""
        if not scored_summaries:
            return None

        lines = ["<memory>", "The following are relevant facts from previous conversations:", ""]

        for _score, summary in scored_summaries:
            channel = summary.get('channel', 'unknown')
            persona = summary.get('persona_name', '')
            # Prefer the actual time the memory occurred over when it was summarized
            memory_timestamp = summary.get('last_message_at') or summary.get('created_at')

            # Build label
            label_parts = [f"#{channel}"]
            if persona == 'ambient':
                label_parts.append("ambient")
            if memory_timestamp:
                label_parts.append(_relative_time(memory_timestamp))

            label = ", ".join(label_parts)
            lines.append(f"[{label}]")

            content = summary.get('content', '')
            for fact_line in content.strip().split('\n'):
                if fact_line.strip():
                    lines.append(fact_line)
            lines.append("")

        lines.append("</memory>")
        return "\n".join(lines)

    def _filter_tools_for_persona(self, persona: Persona) -> List[Dict[str, Any]]:
        """Filters available tools by persona config, service bindings, and model compatibility."""
        all_tools = self.tool_manager.get_tool_definitions()
        enabled_tool_names = persona.get_enabled_tools()

        if enabled_tool_names == ['*']:
            tools_for_llm = all_tools
        elif enabled_tool_names:
            tools_for_llm = [tool for tool in all_tools if
                             tool.get('function', {}).get('name') in enabled_tool_names]
        else:
            tools_for_llm = []

        # Filter out tools whose service_binding isn't in the persona's bindings
        bindings = set(persona.get_service_bindings())
        tools_for_llm = [t for t in tools_for_llm
                         if not t.get('service_binding') or t.get('service_binding') in bindings]

        model_prefix = get_model_prefix(persona.get_model_name())
        tools_for_llm = [t for t in tools_for_llm
                         if model_prefix not in MODEL_INCOMPATIBLE_TOOLS.get(
                             t.get('function', {}).get('name'), set())]

        return tools_for_llm

    async def _execute_read_calls(
            self,
            read_calls: List[Dict[str, Any]],
            conversation_history: List[Dict[str, Any]]
    ) -> None:
        """Execute read-only tool calls and append results to history."""
        for call_item in read_calls:
            tool_name: str = call_item.get("name", "")
            tool_args = call_item.get("arguments", {})
            tool_result = await self.tool_manager.execute_tool(tool_name, **tool_args)
            conversation_history.append({
                "role": "tool",
                "tool_call_id": call_item.get("id"),
                "name": tool_name,
                "content": json.dumps(tool_result)
            })

    async def _run_tool_loop(self, ctx: RequestContext) -> Tuple[str, ResponseType, Optional[str]]:
        """Runs the LLM call / tool execution loop up to MAX_TOOL_CALLS iterations.

        Returns (response_text, response_type, tool_context_json).
        tool_context_json is a JSON string of tool call/result messages, or None if no tools were used.
        """
        history_start = len(ctx.conversation_history)
        for i in range(MAX_TOOL_CALLS):
            context_object: Dict[str, Any] = {
                "persona_prompt": ctx.persona.get_prompt(),
                "history": ctx.conversation_history,
                "current_message": {"text": "", "image_url": ctx.image_url if i == 0 else None}
            }
            llm_response, api_payload = await self.text_engine.generate_response(
                ctx.persona.get_config_for_engine(), context_object, tools=ctx.tools_for_llm
            )
            if api_payload:
                self._store_api_request(
                    ctx.user_identifier, ctx.persona_name, api_payload,
                    tools_for_llm=ctx.tools_for_llm if i == 0 else None
                )

            if llm_response.get("type") == "text":
                tool_msgs = ctx.conversation_history[history_start:]
                tool_context_json = json.dumps(tool_msgs) if tool_msgs else None
                return llm_response.get("content", ""), ResponseType.LLM_GENERATION, tool_context_json

            elif llm_response.get("type") == "tool_calls":
                calls = llm_response.get("calls", [])
                ctx.conversation_history.append({"role": "assistant", "tool_calls": calls})

                read_calls = [c for c in calls if c.get("name") not in WRITE_TOOLS]
                write_calls = [c for c in calls if c.get("name") in WRITE_TOOLS]

                await self._execute_read_calls(read_calls, ctx.conversation_history)

                if ctx.persona.get_execution_mode() == ExecutionMode.CONFIRM and write_calls:
                    pending = PendingConfirmation(
                        write_calls=write_calls,
                        conversation_history=ctx.conversation_history,
                        persona_name=ctx.persona_name,
                        tools_for_llm=ctx.tools_for_llm,
                        image_url=ctx.image_url,
                    )
                    self._pending_confirmations[(ctx.user_identifier, ctx.persona_name)] = pending
                    descriptions = [
                        f"- **{wc.get('name')}**: {json.dumps(wc.get('arguments', {}))}"
                        for wc in write_calls
                    ]
                    confirm_msg = "I'd like to perform the following actions:\n" + "\n".join(descriptions)
                    return confirm_msg, ResponseType.PENDING_CONFIRMATION, None

                await self._execute_write_calls(write_calls, ctx.conversation_history)
            else:
                raise LLMCommunicationError("LLM returned an invalid response structure.")

        logger.error(f"Exceeded max tool calls ({MAX_TOOL_CALLS}) for user {ctx.user_identifier}.")
        return "I seem to be stuck in a loop. Could you please clarify your request?", ResponseType.DEV_COMMAND, None

    async def _prepare_request(self, ctx: RequestContext) -> None:
        """Build history, inject long-term memory, filter tools, append user message."""
        ctx.conversation_history, ctx.oldest_interaction_id = self._build_conversation_history(
            ctx.persona, ctx.user_identifier, ctx.channel,
            ctx.server_id, ctx.history_limit
        )

        # Inject long-term memory block before the sliding window
        memory_block = await self._retrieve_memory_block(
            ctx.persona, ctx.user_identifier, ctx.channel,
            ctx.server_id, ctx.conversation_history,
            oldest_interaction_id=ctx.oldest_interaction_id,
        )
        if memory_block:
            ctx.conversation_history.insert(0, {"role": "user", "content": memory_block})

        ctx.tools_for_llm = self._filter_tools_for_persona(ctx.persona)
        ctx.conversation_history.append({"role": "user", "content": ctx.message})

    async def _execute_request(self, ctx: RequestContext) -> Tuple[str, ResponseType, Optional[str]]:
        """Run tool loop and return response."""
        return await self._run_tool_loop(ctx)

    async def generate_response(
            self,
            persona_name: str,
            user_identifier: str,
            channel: str,
            message: str,
            server_id: Optional[str] = None,
            image_url: Optional[str] = None,
            history_limit: Optional[int] = None,
            user_display_name: Optional[str] = None,
            platform_message_id: Optional[str] = None,
            timestamp: Optional[datetime] = None
    ) -> Tuple[str, ResponseType, Optional[int]]:
        command_result: Optional[Dict[str, Any]] = await self.bot_logic.preprocess_message(
            persona_name, user_identifier, message
        )
        if command_result:
            if command_result.get("mutated", False):
                save_personas_to_file(self.personas)
            return command_result["response"], ResponseType.DEV_COMMAND, None

        persona: Optional[Persona] = self.personas.get(persona_name)
        if not persona:
            return "Error: Persona not found.", ResponseType.DEV_COMMAND, None

        ctx = RequestContext(
            persona=persona, persona_name=persona_name,
            user_identifier=user_identifier, channel=channel, message=message,
            server_id=server_id, image_url=image_url,
            history_limit=history_limit, user_display_name=user_display_name,
        )
        try:
            await self._prepare_request(ctx)
            response_text, response_type, tool_context_json = await self._execute_request(ctx)

            # Log user and assistant messages
            user_ts = timestamp or datetime.now()
            self.memory_manager.log_message(
                user_identifier=user_identifier, persona_name=persona_name,
                channel=channel, author_role='user',
                author_name=user_display_name, content=message,
                timestamp=user_ts, server_id=server_id,
                platform_message_id=platform_message_id,
            )
            assistant_id: Optional[int] = None
            if response_type == ResponseType.LLM_GENERATION and response_text and response_text.strip():
                assistant_id = self.memory_manager.log_message(
                    user_identifier=user_identifier, persona_name=persona_name,
                    channel=channel, author_role='assistant',
                    author_name=persona_name, content=response_text,
                    timestamp=datetime.now(), server_id=server_id,
                    tool_context=tool_context_json,
                )

            return response_text, response_type, assistant_id

        except LLMCommunicationError as e:
            logger.error(f"A recoverable LLM communication error occurred for {user_identifier}: {e}")
            if e.api_payload:
                self._store_api_request(
                    user_identifier, persona_name, e.api_payload,
                    tools_for_llm=ctx.tools_for_llm
                )
            error_msg = ("I'm not sure how to continue. Could you please rephrase?" if "empty response" in str(e) else
                         "Error while generating a response: " + str(e))
            return error_msg, ResponseType.DEV_COMMAND, None
        except Exception as e:
            logger.error(f"A critical error occurred in generate_response for {user_identifier}: {e}", exc_info=True)
            return ("An internal error occurred while processing your request.",
                    ResponseType.DEV_COMMAND, None)

    async def resume_pending_confirmation(
            self, user_identifier: str, persona_name: str, approved: bool
    ) -> Tuple[str, ResponseType, Optional[int]]:
        """Resumes a tool execution that was paused for user confirmation."""
        key = (user_identifier, persona_name)
        pending = self._pending_confirmations.pop(key, None)

        if not pending:
            return "No pending confirmation found.", ResponseType.DEV_COMMAND, None

        if time.time() - pending.created_at > PENDING_CONFIRMATION_TIMEOUT:
            return "Confirmation expired. Please try again.", ResponseType.DEV_COMMAND, None

        persona = self.personas.get(pending.persona_name)
        if not persona:
            return "Error: Persona not found.", ResponseType.DEV_COMMAND, None

        conversation_history = pending.conversation_history

        try:
            if approved:
                await self._execute_write_calls(pending.write_calls, conversation_history)
            else:
                self._append_denied_tool_results(pending.write_calls, conversation_history)

            # Continue the LLM conversation with the tool results
            context_object = {
                "persona_prompt": persona.get_prompt(),
                "history": conversation_history,
                "current_message": {"text": "", "image_url": None}
            }
            llm_response, api_payload = await self.text_engine.generate_response(
                persona.get_config_for_engine(), context_object, tools=pending.tools_for_llm
            )
            if api_payload:
                self._store_api_request(
                    user_identifier, persona_name, api_payload,
                    tools_for_llm=pending.tools_for_llm
                )

            final_text = llm_response.get("content", "")

            assistant_id: Optional[int] = None
            if final_text and final_text.strip():
                assistant_id = self.memory_manager.log_message(
                    user_identifier=user_identifier, persona_name=persona_name,
                    channel="",  # Not available in pending context
                    author_role='assistant', author_name=persona_name,
                    content=final_text, timestamp=datetime.now(),
                )

            return final_text, ResponseType.LLM_GENERATION, assistant_id

        except Exception as e:
            logger.error(f"Error resuming pending confirmation for {user_identifier}: {e}", exc_info=True)
            return ("An error occurred while processing the confirmed action.",
                    ResponseType.DEV_COMMAND, None)
