# src/generation_events.py
"""Event dataclasses for the streaming generation pipeline.

Lives outside chat_system to break a circular import: ToolLoop
(`src/tools/tool_loop.py`) yields these events and is imported by
ChatSystem. chat_system re-exports the names so existing call sites
(`from src.chat_system import TokenEvent, DoneEvent, ResponseType`)
continue to work unchanged.
"""

import uuid
from dataclasses import dataclass
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Tuple, Union


def format_internal_error(
    exc: BaseException,
    *,
    scrub: Optional[Callable[[str], object]] = None,
    max_detail: int = 160,
) -> Tuple[str, str]:
    """Build a diagnosable user-facing error string + a correlation id.

    An opaque "internal error" tells neither the operator nor fixr anything.
    We surface the exception *class*, a truncated single-line message, and a
    short ref id. Log the same ref id alongside the full traceback so the two
    can be tied together after the fact — the ref is the only bridge when the
    full trace lives in a log the reader can't reach yet.

    These sites are terminal — the turn ends here, so the message goes to the
    user directly (no LLM left in the loop to mediate it). We therefore also
    nudge the user to rephrase/retry: the [class]/ref is for whoever diagnoses,
    the nudge is for whoever's stuck.

    Security (DP-225): the exception string reaches an external channel
    (Discord/Zammad), so a provider SDK error can leak an auth header or a
    key-in-URL. This module is a hard leaf (no ``src.*`` imports — enforced by
    tests/test_module_boundaries), so the caller injects the secret scrubber
    via ``scrub`` (pass ``get_scrubber().scrub``); it redacts registered vault
    secrets plus unregistered key shapes and never raises. Omitting ``scrub``
    surfaces the raw detail — only safe when the exception can't carry secrets.

    Returns ``(err_id, message)``. The caller logs with ``err_id`` and yields
    an ``ErrorEvent(message=message)``.
    """
    err_id = uuid.uuid4().hex[:8]
    raw = str(exc)
    if scrub is not None:
        raw = str(scrub(raw))
    detail = " ".join(raw.split())
    if len(detail) > max_detail:
        detail = detail[: max_detail - 1] + "…"
    cls = type(exc).__name__
    if detail:
        message = f"Internal error [{cls}] (ref {err_id}): {detail}"
    else:
        message = f"Internal error [{cls}] (ref {err_id})"
    message += " — you may want to rephrase and try again."
    return err_id, message


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()
    PENDING_CONFIRMATION = auto()


@dataclass
class TokenEvent:
    """Incremental text delta in a streaming response."""
    delta: str


@dataclass
class DoneEvent:
    """Terminal event for stream_response — final committed text + ids.

    `ephemeral_chunk_id` (DP-130 history contract) is a stable handle for a
    rendered-but-unpersisted chunk — the parked-confirmation text on a
    PENDING_CONFIRMATION turn, where `assistant_id` is None. It lets a client
    address that chunk without a DB id, and the server reconcile it on
    approve/deny resume (it is the parked confirmation's correlation token).
    None on normal turns (the chunk is addressed by `assistant_id` instead).
    """
    text: str
    response_type: ResponseType
    assistant_id: Optional[int] = None
    user_interaction_id: Optional[int] = None
    ephemeral_chunk_id: Optional[str] = None


@dataclass
class ErrorEvent:
    """Terminal event for stream_response when generation fails."""
    message: str


@dataclass
class PendingConfirmationEvent:
    """One or more write-tool calls parked awaiting user approval (CONFIRM mode).

    Yielded mid-stream by the orchestration kernel when a turn parks writes for
    the universal write-audit gate, *before* the terminal DoneEvent. It carries
    the structured write calls + audit metadata so an interactive surface (e.g.
    the web portal) can render an approve/deny affordance, and a `token` that
    correlates the park with the resume request — guarding against resuming a
    stale park if the model proposed a new set of writes in the meantime.
    `text` is the same human-readable summary the DoneEvent would carry, so a
    non-interactive consumer can still display it.
    """
    text: str
    write_calls: List[Dict[str, Any]]
    persona_name: str
    token: str
    audit_info: Optional[Dict[str, Any]] = None


@dataclass
class ToolCallStartEvent:
    """Tool invocation surfaced mid-stream. `call_id` pairs with the
    matching ToolCallResultEvent so consumers can fold open/close blocks
    even if a future provider streams parallel calls. `group_id` tags
    every call minted by the same model iteration so a future parallel
    executor can render concurrent calls under one header."""
    tool_name: str
    arguments: Dict[str, Any]
    call_id: str
    group_id: Optional[str] = None


@dataclass
class ToolCallResultEvent:
    """Result of a previously-yielded ToolCallStartEvent. `result` is the
    serialized payload the LLM will see; `error` is set on tool execution
    failure (and `result` still carries a fallback string for the model)."""
    call_id: str
    tool_name: str
    result: str
    error: Optional[str] = None
    group_id: Optional[str] = None


GenerationEvent = Union[
    TokenEvent, DoneEvent, ErrorEvent,
    ToolCallStartEvent, ToolCallResultEvent,
    PendingConfirmationEvent,
]
