# src/generation_events.py
"""Event dataclasses for the streaming generation pipeline.

Lives outside chat_system to break a circular import: ToolLoop
(`src/tools/tool_loop.py`) yields these events and is imported by
ChatSystem. chat_system re-exports the names so existing call sites
(`from src.chat_system import TokenEvent, DoneEvent, ResponseType`)
continue to work unchanged.
"""

from dataclasses import dataclass
from enum import Enum, auto
from typing import Any, Dict, Optional, Union


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()
    PENDING_CONFIRMATION = auto()


@dataclass
class TokenEvent:
    """Incremental text delta in a streaming response."""
    delta: str


@dataclass
class DoneEvent:
    """Terminal event for stream_response — final committed text + ids."""
    text: str
    response_type: ResponseType
    assistant_id: Optional[int] = None
    user_interaction_id: Optional[int] = None


@dataclass
class ErrorEvent:
    """Terminal event for stream_response when generation fails."""
    message: str


@dataclass
class ToolCallStartEvent:
    """Tool invocation surfaced mid-stream. `call_id` pairs with the
    matching ToolCallResultEvent so consumers can fold open/close blocks
    even if a future provider streams parallel calls."""
    tool_name: str
    arguments: Dict[str, Any]
    call_id: str


@dataclass
class ToolCallResultEvent:
    """Result of a previously-yielded ToolCallStartEvent. `result` is the
    serialized payload the LLM will see; `error` is set on tool execution
    failure (and `result` still carries a fallback string for the model)."""
    call_id: str
    tool_name: str
    result: str
    error: Optional[str] = None


GenerationEvent = Union[
    TokenEvent, DoneEvent, ErrorEvent,
    ToolCallStartEvent, ToolCallResultEvent,
]
